v1 = int(input('Digite o primeiro valor: '))
v2 = int(input('Digite o segundo valor: '))
v3 = int(input('Digite o terceiro valor: '))
max_value = max(v1, v2, v3)
min_value = min(v1, v2, v3)
print(f'O maior valor é {max_value} e o menor valor é {min_value}.')    