#nome = input ('Digite o seu nome: ')
#print ('Prazer em te conhecer {:20}!'.format(nome))
#print ('Prazer em te conhecer {:<20}!'.format(nome))
#print ('Prazer em te conhecer {:>20}!'.format(nome))
#print ('Prazer em te conhecer {:^20}!'.format(nome))
#print ('Prazer em te conhecer {:=^20}!'.format(nome))
n1 = int (input('Digite um valor:'))
n2 = int (input('Digite outro valor:'))
print (f'A soma vale {n1+n2}')
print (f'A subtração vale {n1-n2}')
print (f'A multiplicação vale {n1*n2}')
print (f'A divisão vale {n1/n2}')
print (f'A potência vale {n1**n2}')
print (f'A divisão inteira vale {n1//n2}')
print (f'O resto da divisão vale {n1%n2}')
